### ISSUE TITLE
UI Overhaul Checklist ;E

### ISSUE THREAD

**Issue by andrewmcodes** [andrewmcodes/onshore-production#32]
- [x] Add icons
- [x] Updates buttons/links
- [x] Animations
- [x] Form redirect
- [ ] Form alert
- [x] No nav link on contact
- [x] button text style isn’t consistent
- [ ] links aren’t discernible enough
- [ ] Webpack img compression isn’t doing anything
